services:
  snowly:
    container_name: snowly
    image: flustix/natsu:latest
    restart: unless-stopped
    environment:
      - TOKEN=your_token_here
      - MONGO_CONNECTION=mongodb://localhost:27017
      - DATABASE=snowly